# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{engineyard-theme}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Paul Campbell"]
  s.date = %q{2011-02-08}
  s.description = %q{a 'pugita_header' and 'pugita_footer' method, along with an assets generator to make any site look like engineyard.com}
  s.email = %q{paul@rslw.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "app/helpers/pugita_engine_helper.rb",
    "app/helpers/static_helper.rb",
    "app/views/pugita/_footer.html.erb",
    "app/views/pugita/_header.html.erb",
    "app/views/shared/_appcloud_signup_button.html.erb",
    "app/views/shared/_contact_sales_button.html.erb",
    "app/views/shared/_countdown.html.erb",
    "app/views/shared/_featured.html.erb",
    "app/views/shared/_global_nav.html.erb",
    "app/views/shared/_livechat_button.html.erb",
    "app/views/shared/_optimizer.html.erb",
    "app/views/shared/_recorded_webinars_sidebar.erb",
    "app/views/shared/_tracking.html.erb",
    "app/views/shared/_video.html.erb",
    "app/views/shared/forms/_regions.html.erb",
    "lib/generators/pugita_header_generator.rb",
    "lib/pugita_header.rb",
    "pugita_header.gemspec"
  ]
  s.homepage = %q{http://github.com/engineyard/engineyard-theme}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.5.0}
  s.summary = %q{A gem providing helper methods and assets to make any site look like engineyard.com}
  s.test_files = [
    "spec/pugita_header_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 3.0.3"])
      s.add_runtime_dependency(%q<sqlite3>, [">= 0"])
      s.add_runtime_dependency(%q<pugita_header>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_runtime_dependency(%q<rails>, ["~> 3"])
    else
      s.add_dependency(%q<rails>, ["= 3.0.3"])
      s.add_dependency(%q<sqlite3>, [">= 0"])
      s.add_dependency(%q<pugita_header>, [">= 0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rails>, ["~> 3"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.0.3"])
    s.add_dependency(%q<sqlite3>, [">= 0"])
    s.add_dependency(%q<pugita_header>, [">= 0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rails>, ["~> 3"])
  end
end

